Use reference to parent span where appropriate
While investigating another issue, I noticed the following panic in the
output of `janus_aggregator`:

```
thread 'tokio-runtime-worker' panicked at <snip>
tried to clone Id(274877906948), but no span exists with that ID
This may be caused by consuming a parent span (`parent: span`) rather
than borrowing it (`parent: &span`).
```

The backtrace pointed me to our usage of the `tracing::info_span` macro.
The error message and documentation ([1]) make it clear enough you're
meant to use a reference to the parent span and not the value. I audited
our usage of `info_span!` and related macros and fixed them all.

[1]: https://docs.rs/tracing/0.1.41/tracing/index.html#using-the-macros