Fix panic in ReportWriter if upload request is cancelled(?).
The response-receiver could be dropped if the entire upload future was
dropped, which I think corresponds to a cancelled request handling. This
would cause the attempt to send the response to panic, which would cause
all other waiting response-receivers to panic themselves when the
respense-sender was dropped. I saw a few instances of this in the logs
from the latest load test:

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Ok(())', /src/aggregator/src/aggregator/report_writer.rs:139:26
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', /src/aggregator/src/aggregator/report_writer.rs:56:23

With this change, any responses whose receivers have been dropped will
simply be dropped.

Also, lower the level of a few spammy-but-less-useful log messages.